### ISSUE TITLE
Time/Date is reset

### ISSUE THREAD

**Issue by AlexRomanovIV** [RC-MODULE/linux-3.10.x#3]
It is Thu Jan  1 00:00:00 UTC 1970 every time when the board has been started.

Is it real to fix it or it's a MB77.07's problem?

**Comment by nekromant** [comment]
There's no real software fix to this, because MB77.07 has no RTC onboard. They've dropped it to cut down the cost. So if the correct date/time is required for your application you have two options: 
- Software: Set up an NTP client, so that MB77.07 will sync time at boot. 
- Hardware: Attach an RTC module to the I2C bus on the extension header X9 on MB77.07

**Comment by AlexRomanovIV** [comment]
ok, understood, thanks
